### ISSUE TITLE
folder location

### ISSUE THREAD

**Issue by ntbk1919** [SiddhiVTripathi/WB-C#1]
@SiddhiVTripathi  Shouldnt presaved models,dataset be inside train_code folder,otherwise The files wont be able to be acccesed inside train.py? 
Also this error?
![image](https://user-images.githubusercontent.com/60788087/98201336-74f7a500-1f55-11eb-90c2-9b5d56bfc8c5.png)

**Comment by SiddhiVTripathi** [comment]
Actually, when you run the script, you run it from the root folder, so you don't get any errors regarding the files.

About the second error, it's an error related to the version of your joblib and scikit-image.
https://colab.research.google.com/drive/1mJz8IPwsqpQ0oa97nGMUqMrpU4Ih0DzH?usp=sharing see my colab notebook here.

**Comment by ntbk1919** [comment]
Thank you once again.
